## db updator : ec2 esg db에 Product 테이블 생성 및 삽입
- Company 테이블 불러와서 Product 데이터프레임과 left join 후 esg db에 Product table  밀어 넣기

In [1]:
# Company 테이블 불러오기

import pandas as pd

import pymysql


# esg_ec2_config 파일 읽어오기
db_config = {}
with open('./esg_ec2_config', 'r') as f:
    for l in f.readlines():
        key, value = l.rstrip().split('=')
        db_config[key] = value

print('DB 연결 시작 !')
try:
    connect=pymysql.connect(**db_config
    )

    print('DB 접속 성공')
    
    #테이블 불러오기
    try:

        sql = '''select * from Company 
            
            ''' #       
        result = pd.read_sql(sql, connect)
        #print(result)
        print('db select 성공!')

    except Exception as e:
        print(e)


except Exception as e:

    print(e)
    print('DB 접속 실패')

company=pd.DataFrame(result)
company

DB 연결 시작 !
DB 접속 성공
db select 성공!

,ID,CmpName,StockCode,Owner,BizNo,EstDate,Address,Industry,Product
0,1,블리츠웨이,369370,배성웅,6408701749,2020-10-20,서울특별시 영등포구 국회대로 638 블리츠웨이빌딩,제조업,기업 인수 및 합병
1,2,석경에이티,357550,임형섭,1348163122,2000-12-18,경기도 안산시 단원구 별망로459번길 24,제조업,바이오 및 전기전자 나노 소재
2,3,지놈앤컴퍼니,314130,"배지수, 박한수, 서영진 (각자 대표이사)",6278700257,2015-09-24,"경기도 성남시 분당구 판교로255번길 35, B동 8층(삼평동, 판교실리콘파크)",제조업,"마이크로바이옴 기반 치료제, 화장품, 건강기능식품"
3,4,프리시젼바이오,335810,김한신,3148608943,2009-09-28,대전시 유성구 테크노2로 306,제조업,체외진단 기기 및 시약
4,5,알체라,347860,황영규,6438700337,2016-06-03,경기도 성남시 분당구 판교로256번길 25 7층(삼평동),정보통신업,"얼굴인식 AI, 이상상황 감지 AI 등"
...,...,...,...,...,...,...,...,...,...
1377,1378,하이록코리아,13030,"문휴건, 문창환 각자대표이사",6038106103,1978-03-18,부산광역시 강서구 녹산산단27로 97,제조업,관이음쇠
1378,1379,SBI인베스트먼트,19550,공동대표이사 이준효 공동대표이사 소우에이이치로,1208164573,1986-11-24,서울특별시 강남구 테헤란로 509엔씨타워1 14층,금융 및 보험업,벤처캐피탈
1379,1380,리더스 기술투자,19570,김형준,1168116053,1986-11-27,서울특별시 강남구 테헤란로 447 KB우준타워 KB우준타워 17층,금융 및 보험업,금융투자
1380,1381,엠벤처투자,19590,홍성혁,1168115961,1986-12-02,서울특별시 강남구 테헤란로87길 36 도심공항타워 2503호,금융 및 보험업,벤처캐피탈
1381,1382,모헨즈,6920,이기명,3128115972,1970-11-24,충남 충남시 풍세면 남관리 195,제조업,레미콘

In [3]:
# product (녹색 및 위해제품 보유 기업 현황(8건) 데이터프레임과 left join)

import pandas as pd
grn_hzd_df=pd.read_csv(r'C:\Users\Choi\workspace\sesac\1212~final_project_ESG\DATA\녹색,위해, 기업정보결합\kosdaq_report_green_hazard_ver4.csv',encoding='cp949')
grn_hzd_df

   CmpName PctType  Year
0     디와이씨       G  2020
1     우리산업       G  2020
2     동원개발       G  2020
3     대원산업       G  2020
4  CJ프레시웨이       H  2020
5   CJ ENM       H  2020
6  CJ프레시웨이       H  2021
7   CJ ENM       H  2021

In [4]:
prt_cmp_merge=pd.merge(grn_hzd_df,company, how='left',left_on='CmpName', right_on='CmpName')
prt_cmp_merge

,CmpName,PctType,Year,ID,StockCode,Owner,BizNo,EstDate,Address,Industry,Product
0,디와이씨,G,2020,165,310870,"이종훈, 김용덕(각자대표이사)",5878101164,2018-10-22,경상북도 경산시 진량읍 공단7로 42 대원리 498번지 디와이씨 주식회사,제조업,자동차 부품
1,우리산업,G,2020,446,215360,김정우,4168602172,2015-04-01,경기도 용인시 기흥구 지삼로 89,제조업,ACTUATOR 등
2,동원개발,G,2020,1315,13120,"장복만, 이성휘 (각자 대표이사)",6048119275,1978-03-31,"부산광역시 수영구 수영로 754 동원빌딩 (민락동,센텀비스타동원)",건설업,도급공사
3,대원산업,G,2020,1358,5710,"허재건, 허재명, 김재덕",1348104254,1968-09-10,경기도 안산시 단원구 원시로 179,제조업,자동차시트
4,CJ프레시웨이,H,2020,1092,51500,정성필,6038111270,1988-10-27,경기도 용인시 기흥구 기곡로 32,도매 및 소매업,"식자재유통, 단체급식"
5,CJ ENM,H,2020,1228,35760,"Ho Sung Kang, Sang Hyun Yoon",1068151510,1994-12-16,서울특별시 서초구 과천대로 870-13,정보통신업,"의류, 생활주방, 가전제품, 보석, 기타"
6,CJ프레시웨이,H,2021,1092,51500,정성필,6038111270,1988-10-27,경기도 용인시 기흥구 기곡로 32,도매 및 소매업,"식자재유통, 단체급식"
7,CJ ENM,H,2021,1228,35760,"Ho Sung Kang, Sang Hyun Yoon",1068151510,1994-12-16,서울특별시 서초구 과천대로 870-13,정보통신업,"의류, 생활주방, 가전제품, 보석, 기타"

In [5]:
# 필요한 컬럼 선택
product_tb=prt_cmp_merge[['ID','Year','PctType']]
product_tb=product_tb.rename(columns={'ID':'CmpID'})
product_tb

   CmpID  Year PctType
0    165  2020       G
1    446  2020       G
2   1315  2020       G
3   1358  2020       G
4   1092  2020       H
5   1228  2020       H
6   1092  2021       H
7   1228  2021       H

In [6]:
# EC2 DB의 Product 테이블 밀어넣기
# Product테이블에 데이터 삽입.

import pandas as pd

product_list=product_tb.values.tolist() #df를 list 로 만들기-> tuple로 만들기

data = list([tuple(x) for x in product_list])

import pymysql


# esg_ec2_config 파일 읽어오기
db_config = {}
with open('./esg_ec2_config', 'r') as f:
    for l in f.readlines():
        key, value = l.rstrip().split('=')
        db_config[key] = value


print('DB 연결 시작 !')
try:
    connect=pymysql.connect(**db_config
    )

    print('DB 접속 성공')
    #테이블 생성
    # create table PK설정주의.
    try:
        with connect.cursor() as cursor:


            sql = '''CREATE TABLE IF NOT EXISTS Product (
            ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
            CmpID int NOT NULL,
            Year varchar(8) NOT NULL,
            PctType varchar(8) NOT NULL
           
            
            )
            '''
            cursor.execute(sql)
            connect.commit()


    except:
        print('테이블 생성 실패')
    try:
        with connect.cursor() as cursor:

            sql = "insert into Product (CmpID,Year,PctType) values (%s,%s,%s)" #       
            cursor.executemany(sql,data) # executemany는 리스트를 받아옴      

            connect.commit()
            #cursor.close() #db연결해제
            print('db insert 성공!')

    except Exception as e:
        print(e)


except Exception as e:

    print(e)
    print('DB 접속 실패')

DB 연결 시작 !
DB 접속 성공
db insert 성공!